version: "3.2"
services:
  sql-server-db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=<SecurePassword@99>
      - ACCEPT_EULA=Y
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume: